apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-k8s
  labels:
    app: nginx-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-k8s
  template:
    metadata:
      labels:
        app: nginx-k8s
    spec:
      containers:
      - name: nginx-k8s
        image: gauravjot/projectincloud:simple-html
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-k8s-service
spec:
  type: NodePort
  selector:
    app: nginx-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80