name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  
    - name: Save to Azure Storage
      uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
      with:
        # npm builds the app in build directory
        source-path: build
        sas-url: ${{ secrets.DEPLOY_SAS_URL }}
        # name of azure container
        container: staging